### ISSUE TITLE
return a wrong list

### ISSUE THREAD

**Issue by pharazone** [RonenNess/UnityUtils#4]
I followed the usage to put it to my script, but when I run it, the point list return a 0 list.

**Comment by RonenNess** [comment]
Empty list means it didn't find any possible path to destination.

The script works on multiple projects and either way I can't help you without any data. 
Please debug your code and if you do find any real bug, open an issue with detailed information and a way to reproduce it.

Thanks,

**Comment by pharazone** [comment]
Thank you. Here are some code:

![image](https://user-images.githubusercontent.com/11215634/44957860-d6510300-af09-11e8-92e7-6de7ee9e45ae.png)
![image](https://user-images.githubusercontent.com/11215634/44957867-ebc62d00-af09-11e8-8ae4-093820dd3d47.png)

**Comment by RonenNess** [comment]
No dude this is not helping I know why the code returns empty list - because it didn't find a path. That's normal.

However, if there is in fact a path and it didn't find it due to a bug, then it's something to open an issue for. But how can I tell if I don't know the grid you sent it? For all I know you could have send it a grid full of blocks...

So here's what you should do:

1. Debug the code to make sure there's a real bug in *my* code, not in yours.
2. Provide me with a minimal reproduction code that I can run on my PC and see it.

Thanks,

**Comment by RonenNess** [comment]
Ofc it won't work you never init your grid so it's all 0s (blocking).

See that in my docs example code I wrote:


> // set values here....
> // every float in the array represent the cost of passing the tile at that position.
> // use 0.0f for blocking tiles.


That's the part where you supposed to set your grid....

**Comment by pharazone** [comment]
Thanks, dude, I will try it again.

**Comment by RonenNess** [comment]
I suggest trying to set them all to 1s (non blocking) just to see that it works, then start setting up your actual level grid.

Cheers.

**Comment by pharazone** [comment]
It works! Thank you very much! And I made something wrong before, it's my fault. So I'm gonna make the hero walk through the path tonight, thanks again from China!
![image](https://user-images.githubusercontent.com/11215634/44970823-ec9ca480-af85-11e8-8324-4907c107f4e8.png)
